spring :
  application:
    name: Houmi_backend
  datasource:
    url: jdbc:mysql://localhost:3306/houmi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 86400
server:
  servlet:
    context-path: /api
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #??????
  global-config:
    db-config:
      logic-not-delete-value: 0  #?????????
      logic-delete-value: 1  #????????
      logic-delete-field: isDelete #???????????

# ??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example,center.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh-CN
